version: "3.8"

services:

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes: 
      - dbdata:/var/lib/postgresql/data

  web:
    build: ./
    depends_on:
      - "database"

    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4650
    ports:
      - 8080:8080
volumes:
  dbdata: